### ISSUE TITLE
Update for new SMASH version

### ISSUE THREAD

**Issue by NGoetz** [smash-transport/smash-hadron-sampler#27]
`OutputInterface::at_eventend` has changed on the SMASH side, so we have to update the function call https://github.com/smash-transport/smash-devel/blob/9d501d857775df844782ff967e0e19144f7e6f6e/src/oscaroutput.cc#L171

**Comment by zpauliny** [comment]
My mistake @NGoetz complaining about this, I must have used an older version of one of the two softwares, because in fact, this has already been adressed by Renan in PR #26. Everything works as it should, I am closing the issue.
